version: "3.2"
services:

  server:
    build: ./server
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: $SERVER
        target: /go/src/github.com/benoctopus/server

  client:
    build: ./web
    depends_on:
      - db
      - server
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: $CLIENT
        target: /web

  db:
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD secretPassword
    volumes:
      - "database:/var/lib/mysql"


volumes:
  database: