version: "3"
services:

  server:
    build: ./server
    depends_on:
      - database
    ports:
      - "8080:80"
    entrypoint: "tail -f /dev/null"
    volumes:
      - .:go/src/github.com/WillAndBensExcellentAdventure/simple_trello

  db:
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD secretPassword
    volumes:
      "database:/var/lib/mysql


volumes:
  database: